ul-style:
  style: dash
ul-indent:
  indent: 2
commands-show-output: false
no-bare-urls: false
line-length: false
heading-increment: false
no-duplicate-heading: false
first-line-heading: false
blanks-around-headings: false
